from __future__ import annotations

from typing import Dict, List


def _case(label: str, payload: Dict[str, object]) -> Dict[str, object]:
    out = {"_case_label": label}
    out.update(payload)
    return out


def burnup_family_candidates() -> List[Dict[str, object]]:
    return [
        _case(
            "single_long_hold",
            {"sequence_count": 1, "burnup_steps_1": 100, "rod_1": 225},
        ),
        _case(
            "two_stage_soft_pull",
            {"sequence_count": 2, "burnup_steps_1": 60, "rod_1": 200, "burnup_steps_2": 40, "rod_2": 180},
        ),
        _case(
            "three_stage_gradual_pull",
            {
                "sequence_count": 3,
                "burnup_steps_1": 30,
                "rod_1": 225,
                "burnup_steps_2": 40,
                "rod_2": 210,
                "burnup_steps_3": 30,
                "rod_3": 195,
            },
        ),
        _case(
            "two_stage_front_loaded",
            {"sequence_count": 2, "burnup_steps_1": 80, "rod_1": 215, "burnup_steps_2": 20, "rod_2": 190},
        ),
        _case(
            "three_stage_low_rod_terminal",
            {
                "sequence_count": 3,
                "burnup_steps_1": 40,
                "rod_1": 220,
                "burnup_steps_2": 35,
                "rod_2": 205,
                "burnup_steps_3": 25,
                "rod_3": 175,
            },
        ),
        _case(
            "three_stage_mid_hold",
            {
                "sequence_count": 3,
                "burnup_steps_1": 25,
                "rod_1": 210,
                "burnup_steps_2": 50,
                "rod_2": 210,
                "burnup_steps_3": 25,
                "rod_3": 210,
            },
        ),
        _case(
            "two_stage_balanced_150",
            {"sequence_count": 2, "burnup_steps_1": 75, "rod_1": 225, "burnup_steps_2": 75, "rod_2": 225},
        ),
        _case(
            "two_stage_split_pull_150",
            {"sequence_count": 2, "burnup_steps_1": 80, "rod_1": 225, "burnup_steps_2": 70, "rod_2": 215},
        ),
        _case(
            "two_stage_front_loaded_150",
            {"sequence_count": 2, "burnup_steps_1": 90, "rod_1": 225, "burnup_steps_2": 60, "rod_2": 220},
        ),
        _case(
            "two_stage_anchor_150",
            {"sequence_count": 2, "burnup_steps_1": 100, "rod_1": 225, "burnup_steps_2": 50, "rod_2": 220},
        ),
        _case(
            "two_stage_anchor_150_flat_tail",
            {"sequence_count": 2, "burnup_steps_1": 100, "rod_1": 225, "burnup_steps_2": 50, "rod_2": 225},
        ),
        _case(
            "two_stage_anchor_150_low_tail",
            {"sequence_count": 2, "burnup_steps_1": 100, "rod_1": 225, "burnup_steps_2": 50, "rod_2": 215},
        ),
        _case(
            "three_stage_flat_150",
            {
                "sequence_count": 3,
                "burnup_steps_1": 50,
                "rod_1": 225,
                "burnup_steps_2": 50,
                "rod_2": 225,
                "burnup_steps_3": 50,
                "rod_3": 225,
            },
        ),
        _case(
            "three_stage_soft_pull_150",
            {
                "sequence_count": 3,
                "burnup_steps_1": 50,
                "rod_1": 225,
                "burnup_steps_2": 50,
                "rod_2": 220,
                "burnup_steps_3": 50,
                "rod_3": 215,
            },
        ),
    ]


def xenon_family_candidates() -> List[Dict[str, object]]:
    return [
        _case(
            "two_step_low_power_hold",
            {
                "xenon_steps": 2,
                "step_1": 1.0,
                "change_state_1": "True",
                "power_1": 0.3,
                "rod_1": 225,
                "step_2": 1.0,
                "change_state_2": "True",
                "power_2": 0.3,
                "rod_2": 225,
            },
        ),
        _case(
            "two_step_gentle_low_hold",
            {
                "xenon_steps": 2,
                "step_1": 1.0,
                "change_state_1": "True",
                "power_1": 0.25,
                "rod_1": 225,
                "step_2": 1.0,
                "change_state_2": "True",
                "power_2": 0.3,
                "rod_2": 225,
            },
        ),
        _case(
            "two_step_low_hold_soft_rod",
            {
                "xenon_steps": 2,
                "step_1": 1.0,
                "change_state_1": "True",
                "power_1": 0.3,
                "rod_1": 225,
                "step_2": 1.0,
                "change_state_2": "True",
                "power_2": 0.3,
                "rod_2": 220,
            },
        ),
        _case(
            "two_step_ramp_then_hold",
            {
                "xenon_steps": 2,
                "step_1": 1.0,
                "change_state_1": "True",
                "power_1": 0.5,
                "rod_1": 210,
                "step_2": 1.0,
                "change_state_2": "False",
                "power_2": -1.0,
                "rod_2": -1.0,
            },
        ),
        _case(
            "three_step_drop_schedule",
            {
                "xenon_steps": 3,
                "step_1": 1.0,
                "change_state_1": "True",
                "power_1": 0.4,
                "rod_1": 215,
                "step_2": 1.0,
                "change_state_2": "True",
                "power_2": 0.2,
                "rod_2": 205,
                "step_3": 1.0,
                "change_state_3": "False",
                "power_3": -1.0,
                "rod_3": -1.0,
            },
        ),
        _case(
            "three_step_low_plateau",
            {
                "xenon_steps": 3,
                "step_1": 0.5,
                "change_state_1": "True",
                "power_1": 0.25,
                "rod_1": 225,
                "step_2": 1.0,
                "change_state_2": "True",
                "power_2": 0.3,
                "rod_2": 225,
                "step_3": 0.5,
                "change_state_3": "True",
                "power_3": 0.3,
                "rod_3": 220,
            },
        ),
        _case(
            "three_step_plateau",
            {
                "xenon_steps": 3,
                "step_1": 0.5,
                "change_state_1": "True",
                "power_1": 0.45,
                "rod_1": 220,
                "step_2": 1.0,
                "change_state_2": "True",
                "power_2": 0.45,
                "rod_2": 220,
                "step_3": 0.5,
                "change_state_3": "False",
                "power_3": -1.0,
                "rod_3": -1.0,
            },
        ),
        _case(
            "four_step_downshift",
            {
                "xenon_steps": 4,
                "step_1": 0.5,
                "change_state_1": "True",
                "power_1": 0.6,
                "rod_1": 210,
                "step_2": 0.5,
                "change_state_2": "True",
                "power_2": 0.4,
                "rod_2": 205,
                "step_3": 0.5,
                "change_state_3": "True",
                "power_3": 0.2,
                "rod_3": 200,
                "step_4": 0.5,
                "change_state_4": "False",
                "power_4": -1.0,
                "rod_4": -1.0,
            },
        ),
        _case(
            "four_step_recovery",
            {
                "xenon_steps": 4,
                "step_1": 0.5,
                "change_state_1": "True",
                "power_1": 0.25,
                "rod_1": 225,
                "step_2": 0.5,
                "change_state_2": "True",
                "power_2": 0.35,
                "rod_2": 220,
                "step_3": 0.5,
                "change_state_3": "True",
                "power_3": 0.45,
                "rod_3": 215,
                "step_4": 0.5,
                "change_state_4": "False",
                "power_4": -1.0,
                "rod_4": -1.0,
            },
        ),
        _case(
            "four_step_low_hold_recovery",
            {
                "xenon_steps": 4,
                "step_1": 0.5,
                "change_state_1": "True",
                "power_1": 0.2,
                "rod_1": 225,
                "step_2": 0.5,
                "change_state_2": "True",
                "power_2": 0.3,
                "rod_2": 225,
                "step_3": 0.5,
                "change_state_3": "True",
                "power_3": 0.35,
                "rod_3": 220,
                "step_4": 0.5,
                "change_state_4": "False",
                "power_4": -1.0,
                "rod_4": -1.0,
            },
        ),
        _case(
            "four_step_soft_plateau",
            {
                "xenon_steps": 4,
                "step_1": 0.5,
                "change_state_1": "True",
                "power_1": 0.3,
                "rod_1": 225,
                "step_2": 0.5,
                "change_state_2": "True",
                "power_2": 0.3,
                "rod_2": 225,
                "step_3": 0.5,
                "change_state_3": "True",
                "power_3": 0.35,
                "rod_3": 220,
                "step_4": 0.5,
                "change_state_4": "True",
                "power_4": 0.35,
                "rod_4": 220,
            },
        ),
    ]
